#!/bin/bash

DEFAULT_NUMBER_OF_DESKTOPS=20
max_desktops=${1:-$DEFAULT_NUMBER_OF_DESKTOPS}
desktop=0
i=1

monitors=($(bspc query -M --names))
effective_number_of_desktops=$(($max_desktops - ${#monitors[@]}))
max_desktops_per_monitor=$(($effective_number_of_desktops/${#monitors[@]}))

if [ $max_desktops_per_monitor -lt 1 ]; then
    ((max_desktops_per_monitor=1))
fi

for monitor in ${monitors[@]}; do
    bspc monitor $monitor -D 1
    bspc monitor $monitor --reset-desktops 1
    bspc monitor $monitor --remove-desktops 1
    ((desktops=0))
    while [ $desktops -lt $max_desktops_per_monitor ]; do
        ((i++))
        ((desktops++))
        bspc monitor $monitor --add-desktops $i
    done
done

