#!/bin/sh
# bspwm config

# SETTINGS
export _JAVA_AWT_WM_NONREPARENTING=1

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config click_to_focus true

bspc config border_width 0
bspc config window_gap 5

bspc config presel_feedback_color \#EEEEEE

bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true

# UTILS

sxhkd &
nm-applet &
compton &
wal -R &
~/.config/polybar/init.sh &
~/.config/bspwm/scripts/monitor &
